defaults:
  - _self_
  # - experiments: baselines
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

# >> meta <<
cluster: seuss
n_seeds: 1
seed_list: []
ExpID: 9999
ExpGroup: tmp
dry_run: False
quick: True
user: bowenj

# >> variants <<
experiments:
  # ConfigDict to override:
  # - default_kwargs
  # - varaints
  # - skip_variants

# >> hydra related <<
hydra:
  output_subdir: null